// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: internal.proto

#include "internal.pb.h"
#include "internal.grpc.pb.h"

#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace quintet {
namespace rpc {

static const char* Internal_method_names[] = {
  "/quintet.rpc.Internal/AppendEntries",
  "/quintet.rpc.Internal/RequestVote",
};

std::unique_ptr< Internal::Stub> Internal::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Internal::Stub> stub(new Internal::Stub(channel));
  return stub;
}

Internal::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_AppendEntries_(Internal_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_RequestVote_(Internal_method_names[1], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Internal::Stub::AppendEntries(::grpc::ClientContext* context, const ::quintet::rpc::AppendEntriesMessage& request, ::quintet::rpc::AppendEntriesReply* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_AppendEntries_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::quintet::rpc::AppendEntriesReply>* Internal::Stub::AsyncAppendEntriesRaw(::grpc::ClientContext* context, const ::quintet::rpc::AppendEntriesMessage& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::quintet::rpc::AppendEntriesReply>::Create(channel_.get(), cq, rpcmethod_AppendEntries_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::quintet::rpc::AppendEntriesReply>* Internal::Stub::PrepareAsyncAppendEntriesRaw(::grpc::ClientContext* context, const ::quintet::rpc::AppendEntriesMessage& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::quintet::rpc::AppendEntriesReply>::Create(channel_.get(), cq, rpcmethod_AppendEntries_, context, request, false);
}

::grpc::Status Internal::Stub::RequestVote(::grpc::ClientContext* context, const ::quintet::rpc::RequestVoteMessage& request, ::quintet::rpc::RequestVoteReply* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_RequestVote_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::quintet::rpc::RequestVoteReply>* Internal::Stub::AsyncRequestVoteRaw(::grpc::ClientContext* context, const ::quintet::rpc::RequestVoteMessage& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::quintet::rpc::RequestVoteReply>::Create(channel_.get(), cq, rpcmethod_RequestVote_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::quintet::rpc::RequestVoteReply>* Internal::Stub::PrepareAsyncRequestVoteRaw(::grpc::ClientContext* context, const ::quintet::rpc::RequestVoteMessage& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::quintet::rpc::RequestVoteReply>::Create(channel_.get(), cq, rpcmethod_RequestVote_, context, request, false);
}

Internal::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Internal_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Internal::Service, ::quintet::rpc::AppendEntriesMessage, ::quintet::rpc::AppendEntriesReply>(
          std::mem_fn(&Internal::Service::AppendEntries), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Internal_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Internal::Service, ::quintet::rpc::RequestVoteMessage, ::quintet::rpc::RequestVoteReply>(
          std::mem_fn(&Internal::Service::RequestVote), this)));
}

Internal::Service::~Service() {
}

::grpc::Status Internal::Service::AppendEntries(::grpc::ServerContext* context, const ::quintet::rpc::AppendEntriesMessage* request, ::quintet::rpc::AppendEntriesReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Internal::Service::RequestVote(::grpc::ServerContext* context, const ::quintet::rpc::RequestVoteMessage* request, ::quintet::rpc::RequestVoteReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace quintet
}  // namespace rpc

