// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: Quintet.proto

#include "rpc/Quintet.pb.h"
#include "rpc/Quintet.grpc.pb.h"

#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace quintet {
namespace rpc {

static const char* External_method_names[] = {
  "/quintet.rpc.External/call",
};

std::unique_ptr< External::Stub> External::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< External::Stub> stub(new External::Stub(channel));
  return stub;
}

External::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_call_(External_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status External::Stub::call(::grpc::ClientContext* context, const ::quintet::rpc::PbExternalMessage& request, ::quintet::rpc::PbExternalReply* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_call_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::quintet::rpc::PbExternalReply>* External::Stub::AsynccallRaw(::grpc::ClientContext* context, const ::quintet::rpc::PbExternalMessage& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::quintet::rpc::PbExternalReply>::Create(channel_.get(), cq, rpcmethod_call_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::quintet::rpc::PbExternalReply>* External::Stub::PrepareAsynccallRaw(::grpc::ClientContext* context, const ::quintet::rpc::PbExternalMessage& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::quintet::rpc::PbExternalReply>::Create(channel_.get(), cq, rpcmethod_call_, context, request, false);
}

External::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      External_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< External::Service, ::quintet::rpc::PbExternalMessage, ::quintet::rpc::PbExternalReply>(
          std::mem_fn(&External::Service::call), this)));
}

External::Service::~Service() {
}

::grpc::Status External::Service::call(::grpc::ServerContext* context, const ::quintet::rpc::PbExternalMessage* request, ::quintet::rpc::PbExternalReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace quintet
}  // namespace rpc

