// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RaftRpc.proto

#ifndef PROTOBUF_RaftRpc_2eproto__INCLUDED
#define PROTOBUF_RaftRpc_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_RaftRpc_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[7];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsPbReplyImpl();
void InitDefaultsPbReply();
void InitDefaultsPbServerIdImpl();
void InitDefaultsPbServerId();
void InitDefaultsPbLogEntryImpl();
void InitDefaultsPbLogEntry();
void InitDefaultsPbAppendEntriesMessageImpl();
void InitDefaultsPbAppendEntriesMessage();
void InitDefaultsPbRequestVoteMessageImpl();
void InitDefaultsPbRequestVoteMessage();
void InitDefaultsPbAddLogMessageImpl();
void InitDefaultsPbAddLogMessage();
void InitDefaultsPbAddLogReplyImpl();
void InitDefaultsPbAddLogReply();
inline void InitDefaults() {
  InitDefaultsPbReply();
  InitDefaultsPbServerId();
  InitDefaultsPbLogEntry();
  InitDefaultsPbAppendEntriesMessage();
  InitDefaultsPbRequestVoteMessage();
  InitDefaultsPbAddLogMessage();
  InitDefaultsPbAddLogReply();
}
}  // namespace protobuf_RaftRpc_2eproto
namespace quintet {
namespace rpc {
class PbAddLogMessage;
class PbAddLogMessageDefaultTypeInternal;
extern PbAddLogMessageDefaultTypeInternal _PbAddLogMessage_default_instance_;
class PbAddLogReply;
class PbAddLogReplyDefaultTypeInternal;
extern PbAddLogReplyDefaultTypeInternal _PbAddLogReply_default_instance_;
class PbAppendEntriesMessage;
class PbAppendEntriesMessageDefaultTypeInternal;
extern PbAppendEntriesMessageDefaultTypeInternal _PbAppendEntriesMessage_default_instance_;
class PbLogEntry;
class PbLogEntryDefaultTypeInternal;
extern PbLogEntryDefaultTypeInternal _PbLogEntry_default_instance_;
class PbReply;
class PbReplyDefaultTypeInternal;
extern PbReplyDefaultTypeInternal _PbReply_default_instance_;
class PbRequestVoteMessage;
class PbRequestVoteMessageDefaultTypeInternal;
extern PbRequestVoteMessageDefaultTypeInternal _PbRequestVoteMessage_default_instance_;
class PbServerId;
class PbServerIdDefaultTypeInternal;
extern PbServerIdDefaultTypeInternal _PbServerId_default_instance_;
}  // namespace rpc
}  // namespace quintet
namespace quintet {
namespace rpc {

// ===================================================================

class PbReply : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:quintet.rpc.PbReply) */ {
 public:
  PbReply();
  virtual ~PbReply();

  PbReply(const PbReply& from);

  inline PbReply& operator=(const PbReply& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PbReply(PbReply&& from) noexcept
    : PbReply() {
    *this = ::std::move(from);
  }

  inline PbReply& operator=(PbReply&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const PbReply& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PbReply* internal_default_instance() {
    return reinterpret_cast<const PbReply*>(
               &_PbReply_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(PbReply* other);
  friend void swap(PbReply& a, PbReply& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PbReply* New() const PROTOBUF_FINAL { return New(NULL); }

  PbReply* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PbReply& from);
  void MergeFrom(const PbReply& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PbReply* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint64 term = 1;
  void clear_term();
  static const int kTermFieldNumber = 1;
  ::google::protobuf::uint64 term() const;
  void set_term(::google::protobuf::uint64 value);

  // bool ans = 2;
  void clear_ans();
  static const int kAnsFieldNumber = 2;
  bool ans() const;
  void set_ans(bool value);

  // @@protoc_insertion_point(class_scope:quintet.rpc.PbReply)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint64 term_;
  bool ans_;
  mutable int _cached_size_;
  friend struct ::protobuf_RaftRpc_2eproto::TableStruct;
  friend void ::protobuf_RaftRpc_2eproto::InitDefaultsPbReplyImpl();
};
// -------------------------------------------------------------------

class PbServerId : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:quintet.rpc.PbServerId) */ {
 public:
  PbServerId();
  virtual ~PbServerId();

  PbServerId(const PbServerId& from);

  inline PbServerId& operator=(const PbServerId& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PbServerId(PbServerId&& from) noexcept
    : PbServerId() {
    *this = ::std::move(from);
  }

  inline PbServerId& operator=(PbServerId&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const PbServerId& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PbServerId* internal_default_instance() {
    return reinterpret_cast<const PbServerId*>(
               &_PbServerId_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(PbServerId* other);
  friend void swap(PbServerId& a, PbServerId& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PbServerId* New() const PROTOBUF_FINAL { return New(NULL); }

  PbServerId* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PbServerId& from);
  void MergeFrom(const PbServerId& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PbServerId* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string addr = 1;
  void clear_addr();
  static const int kAddrFieldNumber = 1;
  const ::std::string& addr() const;
  void set_addr(const ::std::string& value);
  #if LANG_CXX11
  void set_addr(::std::string&& value);
  #endif
  void set_addr(const char* value);
  void set_addr(const char* value, size_t size);
  ::std::string* mutable_addr();
  ::std::string* release_addr();
  void set_allocated_addr(::std::string* addr);

  // uint32 port = 2;
  void clear_port();
  static const int kPortFieldNumber = 2;
  ::google::protobuf::uint32 port() const;
  void set_port(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:quintet.rpc.PbServerId)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr addr_;
  ::google::protobuf::uint32 port_;
  mutable int _cached_size_;
  friend struct ::protobuf_RaftRpc_2eproto::TableStruct;
  friend void ::protobuf_RaftRpc_2eproto::InitDefaultsPbServerIdImpl();
};
// -------------------------------------------------------------------

class PbLogEntry : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:quintet.rpc.PbLogEntry) */ {
 public:
  PbLogEntry();
  virtual ~PbLogEntry();

  PbLogEntry(const PbLogEntry& from);

  inline PbLogEntry& operator=(const PbLogEntry& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PbLogEntry(PbLogEntry&& from) noexcept
    : PbLogEntry() {
    *this = ::std::move(from);
  }

  inline PbLogEntry& operator=(PbLogEntry&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const PbLogEntry& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PbLogEntry* internal_default_instance() {
    return reinterpret_cast<const PbLogEntry*>(
               &_PbLogEntry_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(PbLogEntry* other);
  friend void swap(PbLogEntry& a, PbLogEntry& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PbLogEntry* New() const PROTOBUF_FINAL { return New(NULL); }

  PbLogEntry* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PbLogEntry& from);
  void MergeFrom(const PbLogEntry& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PbLogEntry* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string opName = 2;
  void clear_opname();
  static const int kOpNameFieldNumber = 2;
  const ::std::string& opname() const;
  void set_opname(const ::std::string& value);
  #if LANG_CXX11
  void set_opname(::std::string&& value);
  #endif
  void set_opname(const char* value);
  void set_opname(const char* value, size_t size);
  ::std::string* mutable_opname();
  ::std::string* release_opname();
  void set_allocated_opname(::std::string* opname);

  // string args = 3;
  void clear_args();
  static const int kArgsFieldNumber = 3;
  const ::std::string& args() const;
  void set_args(const ::std::string& value);
  #if LANG_CXX11
  void set_args(::std::string&& value);
  #endif
  void set_args(const char* value);
  void set_args(const char* value, size_t size);
  ::std::string* mutable_args();
  ::std::string* release_args();
  void set_allocated_args(::std::string* args);

  // .quintet.rpc.PbServerId srvId = 5;
  bool has_srvid() const;
  void clear_srvid();
  static const int kSrvIdFieldNumber = 5;
  const ::quintet::rpc::PbServerId& srvid() const;
  ::quintet::rpc::PbServerId* release_srvid();
  ::quintet::rpc::PbServerId* mutable_srvid();
  void set_allocated_srvid(::quintet::rpc::PbServerId* srvid);

  // uint64 term = 1;
  void clear_term();
  static const int kTermFieldNumber = 1;
  ::google::protobuf::uint64 term() const;
  void set_term(::google::protobuf::uint64 value);

  // uint64 prmIdx = 4;
  void clear_prmidx();
  static const int kPrmIdxFieldNumber = 4;
  ::google::protobuf::uint64 prmidx() const;
  void set_prmidx(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:quintet.rpc.PbLogEntry)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr opname_;
  ::google::protobuf::internal::ArenaStringPtr args_;
  ::quintet::rpc::PbServerId* srvid_;
  ::google::protobuf::uint64 term_;
  ::google::protobuf::uint64 prmidx_;
  mutable int _cached_size_;
  friend struct ::protobuf_RaftRpc_2eproto::TableStruct;
  friend void ::protobuf_RaftRpc_2eproto::InitDefaultsPbLogEntryImpl();
};
// -------------------------------------------------------------------

class PbAppendEntriesMessage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:quintet.rpc.PbAppendEntriesMessage) */ {
 public:
  PbAppendEntriesMessage();
  virtual ~PbAppendEntriesMessage();

  PbAppendEntriesMessage(const PbAppendEntriesMessage& from);

  inline PbAppendEntriesMessage& operator=(const PbAppendEntriesMessage& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PbAppendEntriesMessage(PbAppendEntriesMessage&& from) noexcept
    : PbAppendEntriesMessage() {
    *this = ::std::move(from);
  }

  inline PbAppendEntriesMessage& operator=(PbAppendEntriesMessage&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const PbAppendEntriesMessage& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PbAppendEntriesMessage* internal_default_instance() {
    return reinterpret_cast<const PbAppendEntriesMessage*>(
               &_PbAppendEntriesMessage_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(PbAppendEntriesMessage* other);
  friend void swap(PbAppendEntriesMessage& a, PbAppendEntriesMessage& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PbAppendEntriesMessage* New() const PROTOBUF_FINAL { return New(NULL); }

  PbAppendEntriesMessage* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PbAppendEntriesMessage& from);
  void MergeFrom(const PbAppendEntriesMessage& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PbAppendEntriesMessage* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .quintet.rpc.PbLogEntry logEntries = 5;
  int logentries_size() const;
  void clear_logentries();
  static const int kLogEntriesFieldNumber = 5;
  const ::quintet::rpc::PbLogEntry& logentries(int index) const;
  ::quintet::rpc::PbLogEntry* mutable_logentries(int index);
  ::quintet::rpc::PbLogEntry* add_logentries();
  ::google::protobuf::RepeatedPtrField< ::quintet::rpc::PbLogEntry >*
      mutable_logentries();
  const ::google::protobuf::RepeatedPtrField< ::quintet::rpc::PbLogEntry >&
      logentries() const;

  // .quintet.rpc.PbServerId leaderId = 2;
  bool has_leaderid() const;
  void clear_leaderid();
  static const int kLeaderIdFieldNumber = 2;
  const ::quintet::rpc::PbServerId& leaderid() const;
  ::quintet::rpc::PbServerId* release_leaderid();
  ::quintet::rpc::PbServerId* mutable_leaderid();
  void set_allocated_leaderid(::quintet::rpc::PbServerId* leaderid);

  // uint64 term = 1;
  void clear_term();
  static const int kTermFieldNumber = 1;
  ::google::protobuf::uint64 term() const;
  void set_term(::google::protobuf::uint64 value);

  // uint64 prevLogIdx = 3;
  void clear_prevlogidx();
  static const int kPrevLogIdxFieldNumber = 3;
  ::google::protobuf::uint64 prevlogidx() const;
  void set_prevlogidx(::google::protobuf::uint64 value);

  // uint64 prevLogTerm = 4;
  void clear_prevlogterm();
  static const int kPrevLogTermFieldNumber = 4;
  ::google::protobuf::uint64 prevlogterm() const;
  void set_prevlogterm(::google::protobuf::uint64 value);

  // uint64 commitIdx = 6;
  void clear_commitidx();
  static const int kCommitIdxFieldNumber = 6;
  ::google::protobuf::uint64 commitidx() const;
  void set_commitidx(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:quintet.rpc.PbAppendEntriesMessage)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::quintet::rpc::PbLogEntry > logentries_;
  ::quintet::rpc::PbServerId* leaderid_;
  ::google::protobuf::uint64 term_;
  ::google::protobuf::uint64 prevlogidx_;
  ::google::protobuf::uint64 prevlogterm_;
  ::google::protobuf::uint64 commitidx_;
  mutable int _cached_size_;
  friend struct ::protobuf_RaftRpc_2eproto::TableStruct;
  friend void ::protobuf_RaftRpc_2eproto::InitDefaultsPbAppendEntriesMessageImpl();
};
// -------------------------------------------------------------------

class PbRequestVoteMessage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:quintet.rpc.PbRequestVoteMessage) */ {
 public:
  PbRequestVoteMessage();
  virtual ~PbRequestVoteMessage();

  PbRequestVoteMessage(const PbRequestVoteMessage& from);

  inline PbRequestVoteMessage& operator=(const PbRequestVoteMessage& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PbRequestVoteMessage(PbRequestVoteMessage&& from) noexcept
    : PbRequestVoteMessage() {
    *this = ::std::move(from);
  }

  inline PbRequestVoteMessage& operator=(PbRequestVoteMessage&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const PbRequestVoteMessage& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PbRequestVoteMessage* internal_default_instance() {
    return reinterpret_cast<const PbRequestVoteMessage*>(
               &_PbRequestVoteMessage_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    4;

  void Swap(PbRequestVoteMessage* other);
  friend void swap(PbRequestVoteMessage& a, PbRequestVoteMessage& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PbRequestVoteMessage* New() const PROTOBUF_FINAL { return New(NULL); }

  PbRequestVoteMessage* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PbRequestVoteMessage& from);
  void MergeFrom(const PbRequestVoteMessage& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PbRequestVoteMessage* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .quintet.rpc.PbServerId candidateId = 2;
  bool has_candidateid() const;
  void clear_candidateid();
  static const int kCandidateIdFieldNumber = 2;
  const ::quintet::rpc::PbServerId& candidateid() const;
  ::quintet::rpc::PbServerId* release_candidateid();
  ::quintet::rpc::PbServerId* mutable_candidateid();
  void set_allocated_candidateid(::quintet::rpc::PbServerId* candidateid);

  // uint64 term = 1;
  void clear_term();
  static const int kTermFieldNumber = 1;
  ::google::protobuf::uint64 term() const;
  void set_term(::google::protobuf::uint64 value);

  // uint64 lastLogIdx = 3;
  void clear_lastlogidx();
  static const int kLastLogIdxFieldNumber = 3;
  ::google::protobuf::uint64 lastlogidx() const;
  void set_lastlogidx(::google::protobuf::uint64 value);

  // uint64 lastLogTerm = 4;
  void clear_lastlogterm();
  static const int kLastLogTermFieldNumber = 4;
  ::google::protobuf::uint64 lastlogterm() const;
  void set_lastlogterm(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:quintet.rpc.PbRequestVoteMessage)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::quintet::rpc::PbServerId* candidateid_;
  ::google::protobuf::uint64 term_;
  ::google::protobuf::uint64 lastlogidx_;
  ::google::protobuf::uint64 lastlogterm_;
  mutable int _cached_size_;
  friend struct ::protobuf_RaftRpc_2eproto::TableStruct;
  friend void ::protobuf_RaftRpc_2eproto::InitDefaultsPbRequestVoteMessageImpl();
};
// -------------------------------------------------------------------

class PbAddLogMessage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:quintet.rpc.PbAddLogMessage) */ {
 public:
  PbAddLogMessage();
  virtual ~PbAddLogMessage();

  PbAddLogMessage(const PbAddLogMessage& from);

  inline PbAddLogMessage& operator=(const PbAddLogMessage& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PbAddLogMessage(PbAddLogMessage&& from) noexcept
    : PbAddLogMessage() {
    *this = ::std::move(from);
  }

  inline PbAddLogMessage& operator=(PbAddLogMessage&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const PbAddLogMessage& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PbAddLogMessage* internal_default_instance() {
    return reinterpret_cast<const PbAddLogMessage*>(
               &_PbAddLogMessage_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    5;

  void Swap(PbAddLogMessage* other);
  friend void swap(PbAddLogMessage& a, PbAddLogMessage& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PbAddLogMessage* New() const PROTOBUF_FINAL { return New(NULL); }

  PbAddLogMessage* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PbAddLogMessage& from);
  void MergeFrom(const PbAddLogMessage& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PbAddLogMessage* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string opName = 1;
  void clear_opname();
  static const int kOpNameFieldNumber = 1;
  const ::std::string& opname() const;
  void set_opname(const ::std::string& value);
  #if LANG_CXX11
  void set_opname(::std::string&& value);
  #endif
  void set_opname(const char* value);
  void set_opname(const char* value, size_t size);
  ::std::string* mutable_opname();
  ::std::string* release_opname();
  void set_allocated_opname(::std::string* opname);

  // string args = 2;
  void clear_args();
  static const int kArgsFieldNumber = 2;
  const ::std::string& args() const;
  void set_args(const ::std::string& value);
  #if LANG_CXX11
  void set_args(::std::string&& value);
  #endif
  void set_args(const char* value);
  void set_args(const char* value, size_t size);
  ::std::string* mutable_args();
  ::std::string* release_args();
  void set_allocated_args(::std::string* args);

  // .quintet.rpc.PbServerId srvId = 4;
  bool has_srvid() const;
  void clear_srvid();
  static const int kSrvIdFieldNumber = 4;
  const ::quintet::rpc::PbServerId& srvid() const;
  ::quintet::rpc::PbServerId* release_srvid();
  ::quintet::rpc::PbServerId* mutable_srvid();
  void set_allocated_srvid(::quintet::rpc::PbServerId* srvid);

  // uint64 prmIdx = 3;
  void clear_prmidx();
  static const int kPrmIdxFieldNumber = 3;
  ::google::protobuf::uint64 prmidx() const;
  void set_prmidx(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:quintet.rpc.PbAddLogMessage)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr opname_;
  ::google::protobuf::internal::ArenaStringPtr args_;
  ::quintet::rpc::PbServerId* srvid_;
  ::google::protobuf::uint64 prmidx_;
  mutable int _cached_size_;
  friend struct ::protobuf_RaftRpc_2eproto::TableStruct;
  friend void ::protobuf_RaftRpc_2eproto::InitDefaultsPbAddLogMessageImpl();
};
// -------------------------------------------------------------------

class PbAddLogReply : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:quintet.rpc.PbAddLogReply) */ {
 public:
  PbAddLogReply();
  virtual ~PbAddLogReply();

  PbAddLogReply(const PbAddLogReply& from);

  inline PbAddLogReply& operator=(const PbAddLogReply& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PbAddLogReply(PbAddLogReply&& from) noexcept
    : PbAddLogReply() {
    *this = ::std::move(from);
  }

  inline PbAddLogReply& operator=(PbAddLogReply&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const PbAddLogReply& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PbAddLogReply* internal_default_instance() {
    return reinterpret_cast<const PbAddLogReply*>(
               &_PbAddLogReply_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    6;

  void Swap(PbAddLogReply* other);
  friend void swap(PbAddLogReply& a, PbAddLogReply& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PbAddLogReply* New() const PROTOBUF_FINAL { return New(NULL); }

  PbAddLogReply* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PbAddLogReply& from);
  void MergeFrom(const PbAddLogReply& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PbAddLogReply* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .quintet.rpc.PbServerId leaderId = 2;
  bool has_leaderid() const;
  void clear_leaderid();
  static const int kLeaderIdFieldNumber = 2;
  const ::quintet::rpc::PbServerId& leaderid() const;
  ::quintet::rpc::PbServerId* release_leaderid();
  ::quintet::rpc::PbServerId* mutable_leaderid();
  void set_allocated_leaderid(::quintet::rpc::PbServerId* leaderid);

  // bool success = 1;
  void clear_success();
  static const int kSuccessFieldNumber = 1;
  bool success() const;
  void set_success(bool value);

  // @@protoc_insertion_point(class_scope:quintet.rpc.PbAddLogReply)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::quintet::rpc::PbServerId* leaderid_;
  bool success_;
  mutable int _cached_size_;
  friend struct ::protobuf_RaftRpc_2eproto::TableStruct;
  friend void ::protobuf_RaftRpc_2eproto::InitDefaultsPbAddLogReplyImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PbReply

// uint64 term = 1;
inline void PbReply::clear_term() {
  term_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 PbReply::term() const {
  // @@protoc_insertion_point(field_get:quintet.rpc.PbReply.term)
  return term_;
}
inline void PbReply::set_term(::google::protobuf::uint64 value) {
  
  term_ = value;
  // @@protoc_insertion_point(field_set:quintet.rpc.PbReply.term)
}

// bool ans = 2;
inline void PbReply::clear_ans() {
  ans_ = false;
}
inline bool PbReply::ans() const {
  // @@protoc_insertion_point(field_get:quintet.rpc.PbReply.ans)
  return ans_;
}
inline void PbReply::set_ans(bool value) {
  
  ans_ = value;
  // @@protoc_insertion_point(field_set:quintet.rpc.PbReply.ans)
}

// -------------------------------------------------------------------

// PbServerId

// string addr = 1;
inline void PbServerId::clear_addr() {
  addr_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& PbServerId::addr() const {
  // @@protoc_insertion_point(field_get:quintet.rpc.PbServerId.addr)
  return addr_.GetNoArena();
}
inline void PbServerId::set_addr(const ::std::string& value) {
  
  addr_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:quintet.rpc.PbServerId.addr)
}
#if LANG_CXX11
inline void PbServerId::set_addr(::std::string&& value) {
  
  addr_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:quintet.rpc.PbServerId.addr)
}
#endif
inline void PbServerId::set_addr(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  addr_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:quintet.rpc.PbServerId.addr)
}
inline void PbServerId::set_addr(const char* value, size_t size) {
  
  addr_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:quintet.rpc.PbServerId.addr)
}
inline ::std::string* PbServerId::mutable_addr() {
  
  // @@protoc_insertion_point(field_mutable:quintet.rpc.PbServerId.addr)
  return addr_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PbServerId::release_addr() {
  // @@protoc_insertion_point(field_release:quintet.rpc.PbServerId.addr)
  
  return addr_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PbServerId::set_allocated_addr(::std::string* addr) {
  if (addr != NULL) {
    
  } else {
    
  }
  addr_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), addr);
  // @@protoc_insertion_point(field_set_allocated:quintet.rpc.PbServerId.addr)
}

// uint32 port = 2;
inline void PbServerId::clear_port() {
  port_ = 0u;
}
inline ::google::protobuf::uint32 PbServerId::port() const {
  // @@protoc_insertion_point(field_get:quintet.rpc.PbServerId.port)
  return port_;
}
inline void PbServerId::set_port(::google::protobuf::uint32 value) {
  
  port_ = value;
  // @@protoc_insertion_point(field_set:quintet.rpc.PbServerId.port)
}

// -------------------------------------------------------------------

// PbLogEntry

// uint64 term = 1;
inline void PbLogEntry::clear_term() {
  term_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 PbLogEntry::term() const {
  // @@protoc_insertion_point(field_get:quintet.rpc.PbLogEntry.term)
  return term_;
}
inline void PbLogEntry::set_term(::google::protobuf::uint64 value) {
  
  term_ = value;
  // @@protoc_insertion_point(field_set:quintet.rpc.PbLogEntry.term)
}

// string opName = 2;
inline void PbLogEntry::clear_opname() {
  opname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& PbLogEntry::opname() const {
  // @@protoc_insertion_point(field_get:quintet.rpc.PbLogEntry.opName)
  return opname_.GetNoArena();
}
inline void PbLogEntry::set_opname(const ::std::string& value) {
  
  opname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:quintet.rpc.PbLogEntry.opName)
}
#if LANG_CXX11
inline void PbLogEntry::set_opname(::std::string&& value) {
  
  opname_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:quintet.rpc.PbLogEntry.opName)
}
#endif
inline void PbLogEntry::set_opname(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  opname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:quintet.rpc.PbLogEntry.opName)
}
inline void PbLogEntry::set_opname(const char* value, size_t size) {
  
  opname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:quintet.rpc.PbLogEntry.opName)
}
inline ::std::string* PbLogEntry::mutable_opname() {
  
  // @@protoc_insertion_point(field_mutable:quintet.rpc.PbLogEntry.opName)
  return opname_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PbLogEntry::release_opname() {
  // @@protoc_insertion_point(field_release:quintet.rpc.PbLogEntry.opName)
  
  return opname_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PbLogEntry::set_allocated_opname(::std::string* opname) {
  if (opname != NULL) {
    
  } else {
    
  }
  opname_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), opname);
  // @@protoc_insertion_point(field_set_allocated:quintet.rpc.PbLogEntry.opName)
}

// string args = 3;
inline void PbLogEntry::clear_args() {
  args_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& PbLogEntry::args() const {
  // @@protoc_insertion_point(field_get:quintet.rpc.PbLogEntry.args)
  return args_.GetNoArena();
}
inline void PbLogEntry::set_args(const ::std::string& value) {
  
  args_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:quintet.rpc.PbLogEntry.args)
}
#if LANG_CXX11
inline void PbLogEntry::set_args(::std::string&& value) {
  
  args_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:quintet.rpc.PbLogEntry.args)
}
#endif
inline void PbLogEntry::set_args(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  args_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:quintet.rpc.PbLogEntry.args)
}
inline void PbLogEntry::set_args(const char* value, size_t size) {
  
  args_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:quintet.rpc.PbLogEntry.args)
}
inline ::std::string* PbLogEntry::mutable_args() {
  
  // @@protoc_insertion_point(field_mutable:quintet.rpc.PbLogEntry.args)
  return args_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PbLogEntry::release_args() {
  // @@protoc_insertion_point(field_release:quintet.rpc.PbLogEntry.args)
  
  return args_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PbLogEntry::set_allocated_args(::std::string* args) {
  if (args != NULL) {
    
  } else {
    
  }
  args_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), args);
  // @@protoc_insertion_point(field_set_allocated:quintet.rpc.PbLogEntry.args)
}

// uint64 prmIdx = 4;
inline void PbLogEntry::clear_prmidx() {
  prmidx_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 PbLogEntry::prmidx() const {
  // @@protoc_insertion_point(field_get:quintet.rpc.PbLogEntry.prmIdx)
  return prmidx_;
}
inline void PbLogEntry::set_prmidx(::google::protobuf::uint64 value) {
  
  prmidx_ = value;
  // @@protoc_insertion_point(field_set:quintet.rpc.PbLogEntry.prmIdx)
}

// .quintet.rpc.PbServerId srvId = 5;
inline bool PbLogEntry::has_srvid() const {
  return this != internal_default_instance() && srvid_ != NULL;
}
inline void PbLogEntry::clear_srvid() {
  if (GetArenaNoVirtual() == NULL && srvid_ != NULL) {
    delete srvid_;
  }
  srvid_ = NULL;
}
inline const ::quintet::rpc::PbServerId& PbLogEntry::srvid() const {
  const ::quintet::rpc::PbServerId* p = srvid_;
  // @@protoc_insertion_point(field_get:quintet.rpc.PbLogEntry.srvId)
  return p != NULL ? *p : *reinterpret_cast<const ::quintet::rpc::PbServerId*>(
      &::quintet::rpc::_PbServerId_default_instance_);
}
inline ::quintet::rpc::PbServerId* PbLogEntry::release_srvid() {
  // @@protoc_insertion_point(field_release:quintet.rpc.PbLogEntry.srvId)
  
  ::quintet::rpc::PbServerId* temp = srvid_;
  srvid_ = NULL;
  return temp;
}
inline ::quintet::rpc::PbServerId* PbLogEntry::mutable_srvid() {
  
  if (srvid_ == NULL) {
    srvid_ = new ::quintet::rpc::PbServerId;
  }
  // @@protoc_insertion_point(field_mutable:quintet.rpc.PbLogEntry.srvId)
  return srvid_;
}
inline void PbLogEntry::set_allocated_srvid(::quintet::rpc::PbServerId* srvid) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete srvid_;
  }
  if (srvid) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      srvid = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, srvid, submessage_arena);
    }
    
  } else {
    
  }
  srvid_ = srvid;
  // @@protoc_insertion_point(field_set_allocated:quintet.rpc.PbLogEntry.srvId)
}

// -------------------------------------------------------------------

// PbAppendEntriesMessage

// uint64 term = 1;
inline void PbAppendEntriesMessage::clear_term() {
  term_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 PbAppendEntriesMessage::term() const {
  // @@protoc_insertion_point(field_get:quintet.rpc.PbAppendEntriesMessage.term)
  return term_;
}
inline void PbAppendEntriesMessage::set_term(::google::protobuf::uint64 value) {
  
  term_ = value;
  // @@protoc_insertion_point(field_set:quintet.rpc.PbAppendEntriesMessage.term)
}

// .quintet.rpc.PbServerId leaderId = 2;
inline bool PbAppendEntriesMessage::has_leaderid() const {
  return this != internal_default_instance() && leaderid_ != NULL;
}
inline void PbAppendEntriesMessage::clear_leaderid() {
  if (GetArenaNoVirtual() == NULL && leaderid_ != NULL) {
    delete leaderid_;
  }
  leaderid_ = NULL;
}
inline const ::quintet::rpc::PbServerId& PbAppendEntriesMessage::leaderid() const {
  const ::quintet::rpc::PbServerId* p = leaderid_;
  // @@protoc_insertion_point(field_get:quintet.rpc.PbAppendEntriesMessage.leaderId)
  return p != NULL ? *p : *reinterpret_cast<const ::quintet::rpc::PbServerId*>(
      &::quintet::rpc::_PbServerId_default_instance_);
}
inline ::quintet::rpc::PbServerId* PbAppendEntriesMessage::release_leaderid() {
  // @@protoc_insertion_point(field_release:quintet.rpc.PbAppendEntriesMessage.leaderId)
  
  ::quintet::rpc::PbServerId* temp = leaderid_;
  leaderid_ = NULL;
  return temp;
}
inline ::quintet::rpc::PbServerId* PbAppendEntriesMessage::mutable_leaderid() {
  
  if (leaderid_ == NULL) {
    leaderid_ = new ::quintet::rpc::PbServerId;
  }
  // @@protoc_insertion_point(field_mutable:quintet.rpc.PbAppendEntriesMessage.leaderId)
  return leaderid_;
}
inline void PbAppendEntriesMessage::set_allocated_leaderid(::quintet::rpc::PbServerId* leaderid) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete leaderid_;
  }
  if (leaderid) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      leaderid = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, leaderid, submessage_arena);
    }
    
  } else {
    
  }
  leaderid_ = leaderid;
  // @@protoc_insertion_point(field_set_allocated:quintet.rpc.PbAppendEntriesMessage.leaderId)
}

// uint64 prevLogIdx = 3;
inline void PbAppendEntriesMessage::clear_prevlogidx() {
  prevlogidx_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 PbAppendEntriesMessage::prevlogidx() const {
  // @@protoc_insertion_point(field_get:quintet.rpc.PbAppendEntriesMessage.prevLogIdx)
  return prevlogidx_;
}
inline void PbAppendEntriesMessage::set_prevlogidx(::google::protobuf::uint64 value) {
  
  prevlogidx_ = value;
  // @@protoc_insertion_point(field_set:quintet.rpc.PbAppendEntriesMessage.prevLogIdx)
}

// uint64 prevLogTerm = 4;
inline void PbAppendEntriesMessage::clear_prevlogterm() {
  prevlogterm_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 PbAppendEntriesMessage::prevlogterm() const {
  // @@protoc_insertion_point(field_get:quintet.rpc.PbAppendEntriesMessage.prevLogTerm)
  return prevlogterm_;
}
inline void PbAppendEntriesMessage::set_prevlogterm(::google::protobuf::uint64 value) {
  
  prevlogterm_ = value;
  // @@protoc_insertion_point(field_set:quintet.rpc.PbAppendEntriesMessage.prevLogTerm)
}

// repeated .quintet.rpc.PbLogEntry logEntries = 5;
inline int PbAppendEntriesMessage::logentries_size() const {
  return logentries_.size();
}
inline void PbAppendEntriesMessage::clear_logentries() {
  logentries_.Clear();
}
inline const ::quintet::rpc::PbLogEntry& PbAppendEntriesMessage::logentries(int index) const {
  // @@protoc_insertion_point(field_get:quintet.rpc.PbAppendEntriesMessage.logEntries)
  return logentries_.Get(index);
}
inline ::quintet::rpc::PbLogEntry* PbAppendEntriesMessage::mutable_logentries(int index) {
  // @@protoc_insertion_point(field_mutable:quintet.rpc.PbAppendEntriesMessage.logEntries)
  return logentries_.Mutable(index);
}
inline ::quintet::rpc::PbLogEntry* PbAppendEntriesMessage::add_logentries() {
  // @@protoc_insertion_point(field_add:quintet.rpc.PbAppendEntriesMessage.logEntries)
  return logentries_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::quintet::rpc::PbLogEntry >*
PbAppendEntriesMessage::mutable_logentries() {
  // @@protoc_insertion_point(field_mutable_list:quintet.rpc.PbAppendEntriesMessage.logEntries)
  return &logentries_;
}
inline const ::google::protobuf::RepeatedPtrField< ::quintet::rpc::PbLogEntry >&
PbAppendEntriesMessage::logentries() const {
  // @@protoc_insertion_point(field_list:quintet.rpc.PbAppendEntriesMessage.logEntries)
  return logentries_;
}

// uint64 commitIdx = 6;
inline void PbAppendEntriesMessage::clear_commitidx() {
  commitidx_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 PbAppendEntriesMessage::commitidx() const {
  // @@protoc_insertion_point(field_get:quintet.rpc.PbAppendEntriesMessage.commitIdx)
  return commitidx_;
}
inline void PbAppendEntriesMessage::set_commitidx(::google::protobuf::uint64 value) {
  
  commitidx_ = value;
  // @@protoc_insertion_point(field_set:quintet.rpc.PbAppendEntriesMessage.commitIdx)
}

// -------------------------------------------------------------------

// PbRequestVoteMessage

// uint64 term = 1;
inline void PbRequestVoteMessage::clear_term() {
  term_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 PbRequestVoteMessage::term() const {
  // @@protoc_insertion_point(field_get:quintet.rpc.PbRequestVoteMessage.term)
  return term_;
}
inline void PbRequestVoteMessage::set_term(::google::protobuf::uint64 value) {
  
  term_ = value;
  // @@protoc_insertion_point(field_set:quintet.rpc.PbRequestVoteMessage.term)
}

// .quintet.rpc.PbServerId candidateId = 2;
inline bool PbRequestVoteMessage::has_candidateid() const {
  return this != internal_default_instance() && candidateid_ != NULL;
}
inline void PbRequestVoteMessage::clear_candidateid() {
  if (GetArenaNoVirtual() == NULL && candidateid_ != NULL) {
    delete candidateid_;
  }
  candidateid_ = NULL;
}
inline const ::quintet::rpc::PbServerId& PbRequestVoteMessage::candidateid() const {
  const ::quintet::rpc::PbServerId* p = candidateid_;
  // @@protoc_insertion_point(field_get:quintet.rpc.PbRequestVoteMessage.candidateId)
  return p != NULL ? *p : *reinterpret_cast<const ::quintet::rpc::PbServerId*>(
      &::quintet::rpc::_PbServerId_default_instance_);
}
inline ::quintet::rpc::PbServerId* PbRequestVoteMessage::release_candidateid() {
  // @@protoc_insertion_point(field_release:quintet.rpc.PbRequestVoteMessage.candidateId)
  
  ::quintet::rpc::PbServerId* temp = candidateid_;
  candidateid_ = NULL;
  return temp;
}
inline ::quintet::rpc::PbServerId* PbRequestVoteMessage::mutable_candidateid() {
  
  if (candidateid_ == NULL) {
    candidateid_ = new ::quintet::rpc::PbServerId;
  }
  // @@protoc_insertion_point(field_mutable:quintet.rpc.PbRequestVoteMessage.candidateId)
  return candidateid_;
}
inline void PbRequestVoteMessage::set_allocated_candidateid(::quintet::rpc::PbServerId* candidateid) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete candidateid_;
  }
  if (candidateid) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      candidateid = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, candidateid, submessage_arena);
    }
    
  } else {
    
  }
  candidateid_ = candidateid;
  // @@protoc_insertion_point(field_set_allocated:quintet.rpc.PbRequestVoteMessage.candidateId)
}

// uint64 lastLogIdx = 3;
inline void PbRequestVoteMessage::clear_lastlogidx() {
  lastlogidx_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 PbRequestVoteMessage::lastlogidx() const {
  // @@protoc_insertion_point(field_get:quintet.rpc.PbRequestVoteMessage.lastLogIdx)
  return lastlogidx_;
}
inline void PbRequestVoteMessage::set_lastlogidx(::google::protobuf::uint64 value) {
  
  lastlogidx_ = value;
  // @@protoc_insertion_point(field_set:quintet.rpc.PbRequestVoteMessage.lastLogIdx)
}

// uint64 lastLogTerm = 4;
inline void PbRequestVoteMessage::clear_lastlogterm() {
  lastlogterm_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 PbRequestVoteMessage::lastlogterm() const {
  // @@protoc_insertion_point(field_get:quintet.rpc.PbRequestVoteMessage.lastLogTerm)
  return lastlogterm_;
}
inline void PbRequestVoteMessage::set_lastlogterm(::google::protobuf::uint64 value) {
  
  lastlogterm_ = value;
  // @@protoc_insertion_point(field_set:quintet.rpc.PbRequestVoteMessage.lastLogTerm)
}

// -------------------------------------------------------------------

// PbAddLogMessage

// string opName = 1;
inline void PbAddLogMessage::clear_opname() {
  opname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& PbAddLogMessage::opname() const {
  // @@protoc_insertion_point(field_get:quintet.rpc.PbAddLogMessage.opName)
  return opname_.GetNoArena();
}
inline void PbAddLogMessage::set_opname(const ::std::string& value) {
  
  opname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:quintet.rpc.PbAddLogMessage.opName)
}
#if LANG_CXX11
inline void PbAddLogMessage::set_opname(::std::string&& value) {
  
  opname_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:quintet.rpc.PbAddLogMessage.opName)
}
#endif
inline void PbAddLogMessage::set_opname(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  opname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:quintet.rpc.PbAddLogMessage.opName)
}
inline void PbAddLogMessage::set_opname(const char* value, size_t size) {
  
  opname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:quintet.rpc.PbAddLogMessage.opName)
}
inline ::std::string* PbAddLogMessage::mutable_opname() {
  
  // @@protoc_insertion_point(field_mutable:quintet.rpc.PbAddLogMessage.opName)
  return opname_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PbAddLogMessage::release_opname() {
  // @@protoc_insertion_point(field_release:quintet.rpc.PbAddLogMessage.opName)
  
  return opname_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PbAddLogMessage::set_allocated_opname(::std::string* opname) {
  if (opname != NULL) {
    
  } else {
    
  }
  opname_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), opname);
  // @@protoc_insertion_point(field_set_allocated:quintet.rpc.PbAddLogMessage.opName)
}

// string args = 2;
inline void PbAddLogMessage::clear_args() {
  args_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& PbAddLogMessage::args() const {
  // @@protoc_insertion_point(field_get:quintet.rpc.PbAddLogMessage.args)
  return args_.GetNoArena();
}
inline void PbAddLogMessage::set_args(const ::std::string& value) {
  
  args_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:quintet.rpc.PbAddLogMessage.args)
}
#if LANG_CXX11
inline void PbAddLogMessage::set_args(::std::string&& value) {
  
  args_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:quintet.rpc.PbAddLogMessage.args)
}
#endif
inline void PbAddLogMessage::set_args(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  args_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:quintet.rpc.PbAddLogMessage.args)
}
inline void PbAddLogMessage::set_args(const char* value, size_t size) {
  
  args_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:quintet.rpc.PbAddLogMessage.args)
}
inline ::std::string* PbAddLogMessage::mutable_args() {
  
  // @@protoc_insertion_point(field_mutable:quintet.rpc.PbAddLogMessage.args)
  return args_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PbAddLogMessage::release_args() {
  // @@protoc_insertion_point(field_release:quintet.rpc.PbAddLogMessage.args)
  
  return args_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PbAddLogMessage::set_allocated_args(::std::string* args) {
  if (args != NULL) {
    
  } else {
    
  }
  args_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), args);
  // @@protoc_insertion_point(field_set_allocated:quintet.rpc.PbAddLogMessage.args)
}

// uint64 prmIdx = 3;
inline void PbAddLogMessage::clear_prmidx() {
  prmidx_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 PbAddLogMessage::prmidx() const {
  // @@protoc_insertion_point(field_get:quintet.rpc.PbAddLogMessage.prmIdx)
  return prmidx_;
}
inline void PbAddLogMessage::set_prmidx(::google::protobuf::uint64 value) {
  
  prmidx_ = value;
  // @@protoc_insertion_point(field_set:quintet.rpc.PbAddLogMessage.prmIdx)
}

// .quintet.rpc.PbServerId srvId = 4;
inline bool PbAddLogMessage::has_srvid() const {
  return this != internal_default_instance() && srvid_ != NULL;
}
inline void PbAddLogMessage::clear_srvid() {
  if (GetArenaNoVirtual() == NULL && srvid_ != NULL) {
    delete srvid_;
  }
  srvid_ = NULL;
}
inline const ::quintet::rpc::PbServerId& PbAddLogMessage::srvid() const {
  const ::quintet::rpc::PbServerId* p = srvid_;
  // @@protoc_insertion_point(field_get:quintet.rpc.PbAddLogMessage.srvId)
  return p != NULL ? *p : *reinterpret_cast<const ::quintet::rpc::PbServerId*>(
      &::quintet::rpc::_PbServerId_default_instance_);
}
inline ::quintet::rpc::PbServerId* PbAddLogMessage::release_srvid() {
  // @@protoc_insertion_point(field_release:quintet.rpc.PbAddLogMessage.srvId)
  
  ::quintet::rpc::PbServerId* temp = srvid_;
  srvid_ = NULL;
  return temp;
}
inline ::quintet::rpc::PbServerId* PbAddLogMessage::mutable_srvid() {
  
  if (srvid_ == NULL) {
    srvid_ = new ::quintet::rpc::PbServerId;
  }
  // @@protoc_insertion_point(field_mutable:quintet.rpc.PbAddLogMessage.srvId)
  return srvid_;
}
inline void PbAddLogMessage::set_allocated_srvid(::quintet::rpc::PbServerId* srvid) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete srvid_;
  }
  if (srvid) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      srvid = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, srvid, submessage_arena);
    }
    
  } else {
    
  }
  srvid_ = srvid;
  // @@protoc_insertion_point(field_set_allocated:quintet.rpc.PbAddLogMessage.srvId)
}

// -------------------------------------------------------------------

// PbAddLogReply

// bool success = 1;
inline void PbAddLogReply::clear_success() {
  success_ = false;
}
inline bool PbAddLogReply::success() const {
  // @@protoc_insertion_point(field_get:quintet.rpc.PbAddLogReply.success)
  return success_;
}
inline void PbAddLogReply::set_success(bool value) {
  
  success_ = value;
  // @@protoc_insertion_point(field_set:quintet.rpc.PbAddLogReply.success)
}

// .quintet.rpc.PbServerId leaderId = 2;
inline bool PbAddLogReply::has_leaderid() const {
  return this != internal_default_instance() && leaderid_ != NULL;
}
inline void PbAddLogReply::clear_leaderid() {
  if (GetArenaNoVirtual() == NULL && leaderid_ != NULL) {
    delete leaderid_;
  }
  leaderid_ = NULL;
}
inline const ::quintet::rpc::PbServerId& PbAddLogReply::leaderid() const {
  const ::quintet::rpc::PbServerId* p = leaderid_;
  // @@protoc_insertion_point(field_get:quintet.rpc.PbAddLogReply.leaderId)
  return p != NULL ? *p : *reinterpret_cast<const ::quintet::rpc::PbServerId*>(
      &::quintet::rpc::_PbServerId_default_instance_);
}
inline ::quintet::rpc::PbServerId* PbAddLogReply::release_leaderid() {
  // @@protoc_insertion_point(field_release:quintet.rpc.PbAddLogReply.leaderId)
  
  ::quintet::rpc::PbServerId* temp = leaderid_;
  leaderid_ = NULL;
  return temp;
}
inline ::quintet::rpc::PbServerId* PbAddLogReply::mutable_leaderid() {
  
  if (leaderid_ == NULL) {
    leaderid_ = new ::quintet::rpc::PbServerId;
  }
  // @@protoc_insertion_point(field_mutable:quintet.rpc.PbAddLogReply.leaderId)
  return leaderid_;
}
inline void PbAddLogReply::set_allocated_leaderid(::quintet::rpc::PbServerId* leaderid) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete leaderid_;
  }
  if (leaderid) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      leaderid = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, leaderid, submessage_arena);
    }
    
  } else {
    
  }
  leaderid_ = leaderid;
  // @@protoc_insertion_point(field_set_allocated:quintet.rpc.PbAddLogReply.leaderId)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace rpc
}  // namespace quintet

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_RaftRpc_2eproto__INCLUDED
