// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: RaftRpc.proto
#ifndef GRPC_RaftRpc_2eproto__INCLUDED
#define GRPC_RaftRpc_2eproto__INCLUDED

#include "raft/service/rpc/RaftRpc.pb.h"

#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace quintet {
namespace rpc {

class RaftRpc final {
 public:
  static constexpr char const* service_full_name() {
    return "quintet.rpc.RaftRpc";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status AppendEntries(::grpc::ClientContext* context, const ::quintet::rpc::PbAppendEntriesMessage& request, ::quintet::rpc::PbReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::quintet::rpc::PbReply>> AsyncAppendEntries(::grpc::ClientContext* context, const ::quintet::rpc::PbAppendEntriesMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::quintet::rpc::PbReply>>(AsyncAppendEntriesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::quintet::rpc::PbReply>> PrepareAsyncAppendEntries(::grpc::ClientContext* context, const ::quintet::rpc::PbAppendEntriesMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::quintet::rpc::PbReply>>(PrepareAsyncAppendEntriesRaw(context, request, cq));
    }
    virtual ::grpc::Status RequestVote(::grpc::ClientContext* context, const ::quintet::rpc::PbRequestVoteMessage& request, ::quintet::rpc::PbReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::quintet::rpc::PbReply>> AsyncRequestVote(::grpc::ClientContext* context, const ::quintet::rpc::PbRequestVoteMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::quintet::rpc::PbReply>>(AsyncRequestVoteRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::quintet::rpc::PbReply>> PrepareAsyncRequestVote(::grpc::ClientContext* context, const ::quintet::rpc::PbRequestVoteMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::quintet::rpc::PbReply>>(PrepareAsyncRequestVoteRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::quintet::rpc::PbReply>* AsyncAppendEntriesRaw(::grpc::ClientContext* context, const ::quintet::rpc::PbAppendEntriesMessage& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::quintet::rpc::PbReply>* PrepareAsyncAppendEntriesRaw(::grpc::ClientContext* context, const ::quintet::rpc::PbAppendEntriesMessage& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::quintet::rpc::PbReply>* AsyncRequestVoteRaw(::grpc::ClientContext* context, const ::quintet::rpc::PbRequestVoteMessage& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::quintet::rpc::PbReply>* PrepareAsyncRequestVoteRaw(::grpc::ClientContext* context, const ::quintet::rpc::PbRequestVoteMessage& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status AppendEntries(::grpc::ClientContext* context, const ::quintet::rpc::PbAppendEntriesMessage& request, ::quintet::rpc::PbReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::quintet::rpc::PbReply>> AsyncAppendEntries(::grpc::ClientContext* context, const ::quintet::rpc::PbAppendEntriesMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::quintet::rpc::PbReply>>(AsyncAppendEntriesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::quintet::rpc::PbReply>> PrepareAsyncAppendEntries(::grpc::ClientContext* context, const ::quintet::rpc::PbAppendEntriesMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::quintet::rpc::PbReply>>(PrepareAsyncAppendEntriesRaw(context, request, cq));
    }
    ::grpc::Status RequestVote(::grpc::ClientContext* context, const ::quintet::rpc::PbRequestVoteMessage& request, ::quintet::rpc::PbReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::quintet::rpc::PbReply>> AsyncRequestVote(::grpc::ClientContext* context, const ::quintet::rpc::PbRequestVoteMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::quintet::rpc::PbReply>>(AsyncRequestVoteRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::quintet::rpc::PbReply>> PrepareAsyncRequestVote(::grpc::ClientContext* context, const ::quintet::rpc::PbRequestVoteMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::quintet::rpc::PbReply>>(PrepareAsyncRequestVoteRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< ::quintet::rpc::PbReply>* AsyncAppendEntriesRaw(::grpc::ClientContext* context, const ::quintet::rpc::PbAppendEntriesMessage& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::quintet::rpc::PbReply>* PrepareAsyncAppendEntriesRaw(::grpc::ClientContext* context, const ::quintet::rpc::PbAppendEntriesMessage& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::quintet::rpc::PbReply>* AsyncRequestVoteRaw(::grpc::ClientContext* context, const ::quintet::rpc::PbRequestVoteMessage& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::quintet::rpc::PbReply>* PrepareAsyncRequestVoteRaw(::grpc::ClientContext* context, const ::quintet::rpc::PbRequestVoteMessage& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_AppendEntries_;
    const ::grpc::internal::RpcMethod rpcmethod_RequestVote_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status AppendEntries(::grpc::ServerContext* context, const ::quintet::rpc::PbAppendEntriesMessage* request, ::quintet::rpc::PbReply* response);
    virtual ::grpc::Status RequestVote(::grpc::ServerContext* context, const ::quintet::rpc::PbRequestVoteMessage* request, ::quintet::rpc::PbReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_AppendEntries : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_AppendEntries() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_AppendEntries() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AppendEntries(::grpc::ServerContext* context, const ::quintet::rpc::PbAppendEntriesMessage* request, ::quintet::rpc::PbReply* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAppendEntries(::grpc::ServerContext* context, ::quintet::rpc::PbAppendEntriesMessage* request, ::grpc::ServerAsyncResponseWriter< ::quintet::rpc::PbReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_RequestVote : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_RequestVote() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_RequestVote() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RequestVote(::grpc::ServerContext* context, const ::quintet::rpc::PbRequestVoteMessage* request, ::quintet::rpc::PbReply* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRequestVote(::grpc::ServerContext* context, ::quintet::rpc::PbRequestVoteMessage* request, ::grpc::ServerAsyncResponseWriter< ::quintet::rpc::PbReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_AppendEntries<WithAsyncMethod_RequestVote<Service > > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_AppendEntries : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_AppendEntries() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_AppendEntries() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AppendEntries(::grpc::ServerContext* context, const ::quintet::rpc::PbAppendEntriesMessage* request, ::quintet::rpc::PbReply* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_RequestVote : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_RequestVote() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_RequestVote() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RequestVote(::grpc::ServerContext* context, const ::quintet::rpc::PbRequestVoteMessage* request, ::quintet::rpc::PbReply* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_AppendEntries : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_AppendEntries() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::quintet::rpc::PbAppendEntriesMessage, ::quintet::rpc::PbReply>(std::bind(&WithStreamedUnaryMethod_AppendEntries<BaseClass>::StreamedAppendEntries, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_AppendEntries() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status AppendEntries(::grpc::ServerContext* context, const ::quintet::rpc::PbAppendEntriesMessage* request, ::quintet::rpc::PbReply* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedAppendEntries(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::quintet::rpc::PbAppendEntriesMessage,::quintet::rpc::PbReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_RequestVote : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_RequestVote() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler< ::quintet::rpc::PbRequestVoteMessage, ::quintet::rpc::PbReply>(std::bind(&WithStreamedUnaryMethod_RequestVote<BaseClass>::StreamedRequestVote, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_RequestVote() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status RequestVote(::grpc::ServerContext* context, const ::quintet::rpc::PbRequestVoteMessage* request, ::quintet::rpc::PbReply* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRequestVote(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::quintet::rpc::PbRequestVoteMessage,::quintet::rpc::PbReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_AppendEntries<WithStreamedUnaryMethod_RequestVote<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_AppendEntries<WithStreamedUnaryMethod_RequestVote<Service > > StreamedService;
};

}  // namespace rpc
}  // namespace quintet


#endif  // GRPC_RaftRpc_2eproto__INCLUDED
